# Generated by Django 6.0.6 on 2026-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_customerservice_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='midtrans_token',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
